sudo: false

language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - make tools

install:
  - make deps

before_script:
  - make clean

script:
  - make test

after_success:
  - make coverage
