language: go
go:
  - 1.0
  - 1.1.2
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
branches:
  only:
    - master
install: true
before_script:
  - export PATH=${PATH}:${HOME}/gopath/bin:${GOPATH}
  - travis_retry sudo apt-get install -y --force-yes bc
  - export GO_VERSION=$(go version | perl -ne 'print ($1 || 99.99) if /^.+go([0-9]\.[0-9])|devel/')
  - export FRESH_VERSION=$(go version | perl -ne 'print "true" if /^.+go(1\.(2(\.[23])?|[345]))|devel/')
  - |
    if [ "x${FRESH_VERSION}" == "xtrue" ]; then
      URL="golang.org/x/tools/cmd/cover"
      if [ "x$(echo "$GO_VERSION < 1.4" | bc)" != "x0" ]; then URL="code.google.com/p/go.tools/cmd/cover"; fi
      travis_retry go get -v -x $URL
      travis_retry go get -v -x github.com/axw/gocov/gocov
      export COVER_PROFILE=$(mktemp -t 'cover.XXXXXXXX')
    fi
script:
  - travis_retry go get -v -x github.com/kwilczynski/container/stack
  - |
    if [ "x${FRESH_VERSION}" == "xtrue" ]; then
      go test -v -x -covermode=count -coverprofile=${COVER_PROFILE} $(go list ./...)
      gocov convert $COVER_PROFILE | gocov report
    else
      go test -v -x $(go list ./...)
    fi
