language: go
go:
  - 1.0
  - 1.1.2
  - 1.2.2
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
branches:
  only:
    - master
env:
  - PATH=${PATH}:${HOME}/gopath/bin:${GOPATH}
before_install:
  - make tools
install:
  - make deps
before_script:
  - make clean-all
script:
  - make test
