sudo: false

language: go
go:
  - 1.5.3
  - 1.6
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

branches:
  only:
    - master

before_install:
  - make tools

install:
  - make deps

before_script:
  - make clean

script:
  - make test

after_success:
  - make coverage
